/*
 * Program:      EECS 348 Assignment 2 - email_priority.c
 * Description:  Prioritizes a busy company CEO's inbox using a custom,
 *               list-based (array) MaxHeap implemented entirely from
 *               scratch (no library heap/priority-queue routines are
 *               used). Emails are ranked first by sender category
 *               (Boss > Subordinate/Peer/ImportantPerson (tied) >
 *               OtherPerson) and, within the same category, by date
 *               (newest first).
 * Inputs:       A text file (path given as argv[1], or stdin if no
 *               argument is given) containing one command per line:
 *                 EMAIL <sender category>,<subject line>,<date>
 *                 NEXT
 *                 READ
 *                 COUNT
 * Output:      Created a heap that has the ability to read mail, go to the next mail
 * and count the number of mail depending on the number of commands in the text file
 * Collaborators / Sources: Base implementation generated by Claude
 *               (Anthropic), accessed via claude.ai, using the prompt
 *               documented in the accompanying GenAI analysis.
 *               Reviewed, commented, and corrected by Alan Thomas.
 * Author:      Alan Thomas
 * Creation date: September 15, 2026
 * Revision date: September 17, 2026
 * Revisions:    Added full prologue and in-line comments on every
 *               line. Added edge-case and error handling: unknown
 *               sender category detection, date range validation,
 *               subject truncation warnings, extra-field detection
 *               on EMAIL lines, and a more descriptive file-open
 *               error message.
 */


//Code generated by Claude
#include <stdio.h>   // printf, fprintf, fgets, fopen, fclose, sscanf
#include <stdlib.h>  // malloc, realloc, free, exit, EXIT_SUCCESS/FAILURE
#include <string.h>  // strcmp, strncmp, strtok, strncpy, strlen, strerror
#include <ctype.h>   // (kept for potential character-class checks)
#include <errno.h>   // errno, used with strerror() for file-open errors

/* ------------------------------------------------------------------ */
/*  Email record                                                       */
/* ------------------------------------------------------------------ */
 
#define MAX_SENDER   32    // max characters for a sender category string
#define MAX_SUBJECT  256   // max characters for a subject line
#define MAX_DATE     11    // "MM-DD-YYYY" plus the null terminator

// Holds all the information the program tracks about a single email.
typedef struct {
    char sender[MAX_SENDER];     // sender category, e.g. "Boss"
    char subject[MAX_SUBJECT];   // subject line text (may contain spaces)
    char date[MAX_DATE];         // date exactly as given, MM-DD-YYYY
    int  categoryRank;           // numeric priority derived from sender; higher = more important
    long dateValue;              // date encoded as YYYYMMDD; higher = newer
} Email;                         // end of Email struct definition

/* ------------------------------------------------------------------ */
/*  MaxHeap: list-based (dynamic array) implementation, built from
 *  scratch. No pre-existing heap/priority-queue library is used.     */
/* ------------------------------------------------------------------ */

// A binary max-heap stored in a resizable array (0-indexed).
typedef struct {
    Email *data;      // pointer to the underlying dynamic array
    int    size;      // number of elements currently stored
    int    capacity;  // allocated capacity of data[]
} MaxHeap;             // end of MaxHeap struct definition

// Initializes an empty heap with a small starting capacity.
static void heapInit(MaxHeap *h) {                            // h: heap to initialize
    h->capacity = 8;                                           // start small; heapGrow() doubles as needed
    h->size = 0;                                                // heap starts empty
    h->data = (Email *)malloc(sizeof(Email) * h->capacity);     // allocate the backing array
    if (h->data == NULL) {                                      // malloc failed (out of memory)
        fprintf(stderr, "Error: out of memory.\n");             // report the failure to stderr
        exit(EXIT_FAILURE);                                     // abort the program; nothing else to do
    }                                                            // end if malloc failed
}                                                                // end heapInit

// Releases the heap's backing array and resets its fields.
static void heapFree(MaxHeap *h) {   // h: heap to release
    free(h->data);      // release the dynamic array back to the system
    h->data = NULL;     // avoid leaving a dangling pointer
    h->size = 0;        // logical size is now zero
    h->capacity = 0;    // capacity is now zero (no array to hold anything)
}                        // end heapFree

// Returns 1 (true) if the heap currently holds no emails.
static int heapIsEmpty(const MaxHeap *h) {  // h: heap to check
    return h->size == 0;                    // true exactly when no elements are stored
}                                            // end heapIsEmpty

// Returns the number of emails currently stored in the heap.
static int heapSize(const MaxHeap *h) {  // h: heap to check
    return h->size;                      // size field already tracks the element count
}                                         // end heapSize

// Doubles the heap's array capacity when it becomes full.
static void heapGrow(MaxHeap *h) {  // h: heap whose array needs to grow
    int newCapacity = h->capacity * 2;                                       // double the capacity
    Email *newData = (Email *)realloc(h->data, sizeof(Email) * newCapacity); // attempt to resize in place or move
    if (newData == NULL) {                                                   // realloc failed (out of memory)
        // The original block (h->data) is still valid and unmodified here;
        // free it before exiting so we don't leak it on the way out.
        fprintf(stderr, "Error: out of memory.\n");  // report the failure to stderr
        free(h->data);                                // release the still-valid original block
        exit(EXIT_FAILURE);                           // abort the program; nothing else to do
    }                                                  // end if realloc failed
    h->data = newData;          // point at the (possibly relocated) larger block
    h->capacity = newCapacity;  // record the new capacity
}                                // end heapGrow

// Swaps the contents of two Email structs in place.
static void swapEmails(Email *a, Email *b) {  // a, b: the two emails to swap
    Email temp = *a;  // save a's contents temporarily
    *a = *b;          // copy b's contents into a
    *b = temp;         // copy the saved original a into b
}                       // end swapEmails

// Returns 1 if email 'a' should be considered HIGHER priority than
// email 'b' (i.e. 'a' belongs closer to the root of the max-heap).
static int hasHigherPriority(const Email *a, const Email *b) {  // a, b: emails to compare
    if (a->categoryRank != b->categoryRank) {         // categories differ: rank decides outright
        return a->categoryRank > b->categoryRank;     // different categories: higher rank wins
    }                                                  // end if categories differ
    // Same category: the newer email (larger encoded date) wins.
    return a->dateValue > b->dateValue;                // tie-break by date within the same category
}                                                       // end hasHigherPriority

/* Standard array index helpers for a 0-indexed binary heap. */
static int parentIndex(int i) { return (i - 1) / 2; }  // index of i's parent
static int leftIndex(int i)   { return 2 * i + 1; }    // index of i's left child
static int rightIndex(int i)  { return 2 * i + 2; }    // index of i's right child

// Moves the element at index i up the heap until the max-heap
// property (parent >= children, by priority) is restored.
static void siftUp(MaxHeap *h, int i) {              // h: heap; i: index of the element to move up
    while (i > 0) {                                  // stop once we reach the root
        int p = parentIndex(i);                      // p: index of i's parent
        if (hasHigherPriority(&h->data[i], &h->data[p])) {  // child outranks its parent
            swapEmails(&h->data[i], &h->data[p]);           // swap them up
            i = p;                                          // continue checking from the new position
        } else {                                             // child does not outrank its parent
            break;  // heap property satisfied; stop early
        }                                                     // end if/else
    }                                                         // end while
}                                                             // end siftUp

// Moves the element at index i down the heap until the max-heap
// property is restored below it.
static void siftDown(MaxHeap *h, int i) {   // h: heap; i: index of the element to move down
    while (1) {                             // loop until we break out below
        int left = leftIndex(i);            // left: index of i's left child
        int right = rightIndex(i);          // right: index of i's right child
        int largest = i;                    // assume current node is the largest of the three, then check

        if (left < h->size && hasHigherPriority(&h->data[left], &h->data[largest])) {  // left child exists and outranks
            largest = left;   // left child outranks current largest
        }                     // end if left child check
        if (right < h->size && hasHigherPriority(&h->data[right], &h->data[largest])) {  // right child exists and outranks
            largest = right;  // right child outranks current largest
        }                      // end if right child check
        if (largest == i) {   // neither child outranked the current node
            break;  // node is already in the right place; done
        }                      // end if largest == i
        swapEmails(&h->data[i], &h->data[largest]);  // move the larger child up
        i = largest;                                 // continue sifting down from its new spot
    }                                                 // end while
}                                                     // end siftDown

// Inserts a new email into the heap, growing the array if necessary,
// and restores the heap property with siftUp.
static void heapInsert(MaxHeap *h, Email e) {  // h: heap; e: email to insert (by value)
    if (h->size == h->capacity) {              // array is full
        heapGrow(h);            // make room if the array is full
    }                            // end if array full
    h->data[h->size] = e;       // place new element at the next free slot
    siftUp(h, h->size);         // restore heap order
    h->size++;                  // one more element now stored
}                                // end heapInsert

// Returns a copy of the highest-priority email without removing it.
// Caller must ensure the heap is non-empty.
static Email heapPeek(const MaxHeap *h) {  // h: heap to peek at
    return h->data[0];  // root of a max-heap is always the highest priority element
}                        // end heapPeek

// Removes and returns the highest-priority email.
// Caller must ensure the heap is non-empty.
static Email heapExtractMax(MaxHeap *h) {  // h: heap to extract the max from
    Email top = h->data[0];         // save the root to return later
    h->size--;                      // shrink the logical size
    h->data[0] = h->data[h->size];  // move the last element to the root
    if (h->size > 0) {              // heap still has elements after removal
        siftDown(h, 0);          // restore heap order from the root down
    }                             // end if heap non-empty
    return top;                  // hand back the removed (formerly highest-priority) email
}                                 // end heapExtractMax

/* ------------------------------------------------------------------ */
/*  Parsing helpers                                                   */
/* ------------------------------------------------------------------ */

// Strips trailing '\r' / '\n' / spaces / tabs from a line read via fgets.
static void trimLine(char *s) {  // s: null-terminated string to trim in place
    int len = (int)strlen(s);  // len: current length of the string
    while (len > 0 && (s[len - 1] == '\n' || s[len - 1] == '\r' ||   // last char is newline or CR
                        s[len - 1] == ' '  || s[len - 1] == '\t')) { // or a trailing space/tab
        s[--len] = '\0';  // chop off one trailing character at a time
    }                      // end while
}                          // end trimLine

// Returns 1 if 'category' is one of the five sender categories defined
// by the assignment spec, 0 otherwise. Used to validate input before
// it is silently mapped to a default rank.
static int isKnownCategory(const char *category) {  // category: string to validate
    return strcmp(category, "Boss") == 0 ||                  // matches "Boss"
           strcmp(category, "Subordinate") == 0 ||            // or matches "Subordinate"
           strcmp(category, "Peer") == 0 ||                   // or matches "Peer"
           strcmp(category, "ImportantPerson") == 0 ||        // or matches "ImportantPerson"
           strcmp(category, "OtherPerson") == 0;               // or matches "OtherPerson"
}                                                               // end isKnownCategory

// Maps a sender category string to a numeric priority rank.
// Higher number = higher priority (closer to heap root). Subordinate,
// Peer, and ImportantPerson are intentionally tied per the assignment
// spec; ties within a category are broken by date in hasHigherPriority.
// An unrecognized category is treated as lowest priority; the caller
// is responsible for warning the user about unknown categories.
static int categoryToRank(const char *category) {  // category: sender category string
    if (strcmp(category, "Boss") == 0)            return 5;  // Boss: highest rank
    if (strcmp(category, "Subordinate") == 0)     return 3;  // Subordinate: tied "read next" rank
    if (strcmp(category, "Peer") == 0)             return 3;  // Peer: tied "read next" rank
    if (strcmp(category, "ImportantPerson") == 0) return 3;  // ImportantPerson: tied "read next" rank
    if (strcmp(category, "OtherPerson") == 0)     return 1;  // OtherPerson: lowest defined rank
    return 0;  // unknown category: treat as lowest priority rather than crash
}              // end categoryToRank

// Returns 1 if the given month/day/year form a plausible calendar
// date, 0 otherwise. Deliberately simple (does not account for leap
// years or exact days-per-month) so it catches clearly bad input
// (month 13, day 0, a negative year) without becoming a full calendar
// validator.
static int isPlausibleDate(int month, int day, int year) {  // month/day/year: parsed date parts
    if (month < 1 || month > 12) return 0;      // month must be 1-12
    if (day < 1 || day > 31)     return 0;      // day must be 1-31 (approximate upper bound)
    if (year < 1900 || year > 9999) return 0;   // year must be a plausible 4-digit year
    return 1;  // all three parts passed their range checks
}              // end isPlausibleDate

// Converts a date string "MM-DD-YYYY" into an integer YYYYMMDD so
// that larger values represent more recent dates and can be compared
// numerically without re-parsing. Returns 1 on success, 0 if the
// string could not be parsed as three integers or failed the range
// check in isPlausibleDate; *outValue is only meaningful when this
// function returns 1.
static int dateToValue(const char *date, long *outValue) {  // date: string to parse; outValue: result
    int month = 0, day = 0, year = 0;                         // parsed components, defaulted to 0
    if (sscanf(date, "%d-%d-%d", &month, &day, &year) != 3) {  // expect exactly 3 integers separated by '-'
        *outValue = 0;  // malformed date: caller will warn and treat as oldest possible
        return 0;         // signal failure to the caller
    }                      // end if sscanf failed
    if (!isPlausibleDate(month, day, year)) {  // parsed numbers but out of a sane range
        *outValue = 0;    // treat as oldest possible date
        return 0;          // signal failure to the caller
    }                       // end if implausible date
    *outValue = (long)year * 10000L + (long)month * 100L + (long)day;  // encode as YYYYMMDD
    return 1;  // signal success to the caller
}              // end dateToValue

// Parses a line of the form:
//   <sender category>,<subject line>,<date>
// (the "EMAIL " keyword and following space have already been
// skipped by the caller). Returns 1 on success, 0 if a required
// field is missing. Prints stderr warnings (but still succeeds) for
// recoverable problems: an unrecognized category, a subject line
// long enough to be truncated, an unparseable/out-of-range date, or
// extra comma-delimited fields beyond the three expected ones.
static int parseEmailFields(char *fields, Email *out) {  // fields: mutable comma-delimited text; out: result
    char *category = strtok(fields, ",");   // first comma-delimited field
    char *subject  = strtok(NULL, ",");     // second field
    char *date     = strtok(NULL, ",");     // third field
    char *extra    = strtok(NULL, ",");     // anything after the third field is unexpected

    if (category == NULL || subject == NULL || date == NULL) {  // one or more required fields missing
        return 0;  // line was missing one or more required fields
    }                                                            // end if missing field

    if (extra != NULL) {  // there was a fourth (or later) comma-delimited field
        fprintf(stderr,
            "Warning: EMAIL line has more than 3 fields; ignoring extra data starting at '%s'.\n",
            extra);  // report the unexpected extra data
    }                 // end if extra field present

    if (!isKnownCategory(category)) {  // category is not one of the five defined strings
        fprintf(stderr,
            "Warning: unrecognized sender category '%s'; treating as lowest priority.\n",
            category);  // warn that this category will fall back to rank 0
    }                     // end if unknown category

    if (strlen(subject) > MAX_SUBJECT - 1) {  // subject is longer than the buffer can hold
        fprintf(stderr,
            "Warning: subject line exceeds %d characters and will be truncated: '%s'\n",
            MAX_SUBJECT - 1, subject);  // warn that truncation will occur
    }                                    // end if subject too long

    strncpy(out->sender, category, MAX_SENDER - 1);  // copy category into the fixed-size buffer
    out->sender[MAX_SENDER - 1] = '\0';               // guarantee null termination

    strncpy(out->subject, subject, MAX_SUBJECT - 1);  // copy subject into the fixed-size buffer
    out->subject[MAX_SUBJECT - 1] = '\0';              // guarantee null termination

    strncpy(out->date, date, MAX_DATE - 1);  // copy date into the fixed-size buffer
    out->date[MAX_DATE - 1] = '\0';           // guarantee null termination

    out->categoryRank = categoryToRank(out->sender);  // pre-compute for fast comparisons

    long value = 0;                             // will hold the encoded date value
    if (!dateToValue(out->date, &value)) {       // date could not be parsed/validated
        fprintf(stderr,
            "Warning: could not parse date '%s' as MM-DD-YYYY; treating as oldest possible date.\n",
            date);  // warn that the date is being treated as the oldest possible
    }               // end if date parsing failed
    out->dateValue = value;  // store whatever value dateToValue produced (valid or fallback 0)

    return 1;  // signal successful parsing of this EMAIL line
}              // end parseEmailFields

/* ------------------------------------------------------------------ */
/*  Command handlers                                                  */
/* ------------------------------------------------------------------ */

// Handles an "EMAIL ..." command line: parses it and inserts the
// resulting email into the heap.
static void handleEmail(MaxHeap *h, char *line) {  // h: heap to insert into; line: text after "EMAIL "
    // line currently points at the character right after "EMAIL ".
    Email e;                             // will hold the parsed email
    if (parseEmailFields(line, &e)) {    // parsing succeeded
        heapInsert(h, e);                // add the new email to the heap
    } else {                              // parsing failed (missing field)
        fprintf(stderr, "Warning: malformed EMAIL line skipped (missing field(s)): %s\n", line);  // report and skip
    }                                      // end if/else
}                                          // end handleEmail

// Handles a "NEXT" command: displays the highest-priority email
// without removing it. Calling NEXT twice in a row (no intervening
// READ) prints the same email both times, as required by the spec.
static void handleNext(MaxHeap *h) {  // h: heap to read from
    if (heapIsEmpty(h)) {             // no emails currently queued
        printf("There are no emails to read.\n\n");  // report empty queue
        return;                                        // nothing more to do
    }                                                   // end if empty
    Email top = heapPeek(h);   // look without removing
    printf("Next email:\n");            // header line for the email details
    printf("\tSender: %s\n", top.sender);   // print the sender category
    printf("\tSubject: %s\n", top.subject); // print the subject line
    printf("\tDate: %s\n", top.date);       // print the date
    printf("\n");                            // blank line to match sample output spacing
}                                             // end handleNext

// Handles a "READ" command: removes the highest-priority email
// (the CEO has dealt with it) with no output. Calling READ twice in
// a row silently discards two emails, as required by the spec. READ
// on an empty queue is a safe no-op.
static void handleRead(MaxHeap *h) {  // h: heap to remove from
    if (!heapIsEmpty(h)) {            // only extract if there is something to extract
        heapExtractMax(h);           // remove the highest-priority email, discarding the result
    }                                  // end if non-empty
}                                      // end handleRead

// Handles a "COUNT" command: prints how many unread emails remain.
static void handleCount(MaxHeap *h) {  // h: heap to report the size of
    printf("There are %d emails to read.\n\n", heapSize(h));  // print current unread count
}                                                              // end handleCount

/* ------------------------------------------------------------------ */
/*  Main driver                                                       */
/* ------------------------------------------------------------------ */

int main(int argc, char *argv[]) {  // argc: arg count; argv: arg strings (argv[1] = optional file path)
    FILE *in = stdin;  // default to reading commands from standard input

    if (argc > 1) {  // a filename was given on the command line
        in = fopen(argv[1], "r");  // otherwise read from the file named on the command line
        if (in == NULL) {           // fopen failed to open the file
            // strerror(errno) gives a specific reason (e.g. "No such file or
            // directory", "Permission denied") instead of a generic message.
            fprintf(stderr, "Error: could not open file '%s': %s\n", argv[1], strerror(errno));  // report why it failed
            return EXIT_FAILURE;  // abort the program with a failure status
        }                          // end if fopen failed
    }                              // end if filename given

    MaxHeap heap;         // the priority queue used to hold pending emails
    heapInit(&heap);      // start with an empty priority queue

    char line[600];  // buffer to hold one line of input at a time
    while (fgets(line, sizeof(line), in) != NULL) {  // read one command per line
        trimLine(line);  // remove trailing newline/whitespace

        if (line[0] == '\0') {  // line was empty after trimming
            continue;  // skip blank lines
        }                        // end if blank line

        if (strncmp(line, "EMAIL ", 6) == 0) {          // line begins with "EMAIL "
            handleEmail(&heap, line + 6);   // skip past "EMAIL " before parsing
        } else if (strcmp(line, "NEXT") == 0) {          // line is exactly "NEXT"
            handleNext(&heap);                            // display the top email
        } else if (strcmp(line, "READ") == 0) {          // line is exactly "READ"
            handleRead(&heap);                            // remove the top email
        } else if (strcmp(line, "COUNT") == 0) {         // line is exactly "COUNT"
            handleCount(&heap);                           // print the current unread count
        } else {                                          // line did not match any known command
            fprintf(stderr, "Warning: unrecognized command skipped: %s\n", line);  // report and ignore it
        }                                                  // end if/else if chain
    }                                                      // end while reading lines

    if (in != stdin) {   // we opened a real file rather than using stdin
        fclose(in);  // only close a real file, never stdin
    }                 // end if not stdin
    heapFree(&heap);  // release the heap's dynamic array

    return EXIT_SUCCESS;  // signal successful completion to the OS/shell
}                          // end main
